### ISSUE TITLE
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:

### ISSUE THREAD

**Issue by samikhan69420** [media-kit/media-kit#1067]
flutter_pythonsami@macbook-sami web % flutter build web --release --wasm
Changing current working directory to: /Users/sami/Documents/flutter_projects/my_portfolio

┌─ New feature ────────────────────────────────────────────────────────────────────────────┐
│   WebAssembly compilation is new. Understand the details before deploying to production. │
│   See https://flutter.dev/to/wasm for more information.                                  │
└──────────────────────────────────────────────────────────────────────────────────────────┘

Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.5/lib/src/video_controller/android_video_controller/real.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.5/lib/src/video_controller/native_video_controller/real.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/allocation.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/utf16.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit_video-1.2.5/lib/src/utils/query_decoders.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/initializer_isolate.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/initializer.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/player/real.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/utils/android_asset_loader.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/utils/android_helper.dart:8:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/initializer_native_event_loop.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/utils/android_content_uri_provider.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/utf8.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/arena.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/native_library.dart:8:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../.pub-cache/hosted/pub.dev/media_kit-1.1.11/lib/generated/libmpv/bindings.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi' as ffi;
^
  Command: /Users/sami/Documents/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=/Users/sami/Documents/flutter_projects/my_portfolio/.dart_tool/package_config.json
  --extra-compiler-option=--platform=/Users/sami/Documents/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill -Ddart.vm.profile=false -Ddart.vm.product=true
  --extra-compiler-option=--delete-tostring-package-uri=dart:ui --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/cb4b5fff73850b2e42bd4de7cb9a4310a78ac40d/
  --extra-compiler-option=--depfile=/Users/sami/Documents/flutter_projects/my_portfolio/.dart_tool/flutter_build/bec501df176619283f928e585626ba94/dart2wasm.d -O4 --strip-wasm
  --no-source-maps -o /Users/sami/Documents/flutter_projects/my_portfolio/.dart_tool/flutter_build/bec501df176619283f928e585626ba94/main.dart.wasm
  /Users/sami/Documents/flutter_projects/my_portfolio/.dart_tool/flutter_build/bec501df176619283f928e585626ba94/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:389:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:358:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:891:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:651:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:233:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             46.0s
Error: Failed to compile application for the Web.

**Comment by abdelaziz-mahdy** [comment]
https://github.com/media-kit/media-kit/actions/runs/12446809830/job/34749609852 i think you are not using the github main branch?
```
dependency_overrides: 
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```

**Comment by EArminjon** [comment]
It build well using master (ex: commit 4d8c634c28d439384aab40b9d2edff83077f37c9)

I believe a new pub.dev version is needed.
