### ISSUE TITLE
[GNU/Linux] stray-prints from package:screen_brightness

### ISSUE THREAD

**Issue by ramnycordero** [media-kit/media-kit#302]
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
package:media_kit_libs_linux registered.
Debug service listening on ws://127.0.0.1:36929/gJ71NqeIlbg=/ws
Syncing files to device Linux...
media_kit: VideoOutput: video_output_new: 139686370601392
Cannot load libcuda.so.1
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 139686370601392, id: 94690680129424, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: NativeVideoController: Texture ID: 94690680129424
media_kit: TextureGL: Resize: (1082, 812)
flutter: VideoOutput.Resize
flutter: {handle: 139686370601392, id: 94690680129424, rect: {left: 0, top: 0, width: 1082, height: 812}}
flutter: media_kit: wakelock: _count = 1
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method resetScreenBrightness on channel github.com/aaassseee/screen_brightness)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelScreenBrightness.resetScreenBrightness (package:screen_brightness_platform_interface/method_channel_screen_brightness.dart:125:5)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method resetScreenBrightness on channel github.com/aaassseee/screen_brightness)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelScreenBrightness.resetScreenBrightness (package:screen_brightness_platform_interface/method_channel_screen_brightness.dart:125:5)
<asynchronous suspension>

MediaKitEventLoopHandler::Register: std::thread exit: 139686370601392
MediaKitEventLoopHandler::Dispose: 139686370601392
[FATAL:flutter/fml/thread_local.cc(32)] Check failed: false. pthread_setspecific failed (22): Argumento inválido
```

Other:
On fullscreen don't hide cursor

**Comment by alexmercerind** [comment]
I can't understand, what's the issue???

**Comment by ramnycordero** [comment]
> 

issue, in programming it is an error that must be corrected.
there I added the problem that happens according to the log

**Comment by ramnycordero** [comment]
the compilation works, it works very well, the screensaver problem was corrected.

Ah, I forgot to mention that in fullscreen it does not hide the mouse pointer

**Comment by alexmercerind** [comment]
The redundant logging no longer occurs now. I'm not interested in hiding the mouse cursor in fullscreen, PRs welcomed.

Please [refer to the "Installation" section](https://github.com/media-kit/media-kit#installation) to receive the update.
