### ISSUE TITLE
flutter web complie error 

### ISSUE THREAD

**Issue by inits** [media-kit/media-kit#343]
```
inits@inits-MS-7798:~/Desktop/flutter-project/echo4-dashboard$ flutter  run -d chrome
Launching lib/main.dart on Chrome in debug mode...
../../../.pub-cache/hosted/pub.dev/media_kit_video-1.1.3/lib/src/video/video_texture.dart:118:46: Error: A value of type 'Widget Function(VideoState/*1*/)' can't be assigned to a
variable of type 'Widget Function(VideoState/*2*/)?'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../../works/dataker/data/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'VideoState/*1*/' is from 'package:media_kit_video/src/video/video_web.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-1.1.3/lib/src/video/video_web.dart').
 - 'VideoState/*2*/' is from 'package:media_kit_video/src/video/video_texture.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-1.1.3/lib/src/video/video_texture.dart').
    this.controls = media_kit_video_controls.AdaptiveVideoControls,
                                             ^
Waiting for connection from debug service on Chrome...             64.7s
Failed to compile application.
inits@inits-MS-7798:~/Desktop/flutter-project/echo4-dashboard$ 
```

**Comment by alexmercerind** [comment]
Works for me. Import things correctly.

**Comment by inits** [comment]
# flutter doctor -v
```
inits@i:~/Desktop/aria2c$ flutter  doctor -v



[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.2 LTS 5.19.0-46-generic, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/inits/works/dataker/data/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1



```




# detail error is:

```
--incremental --target=dartdevc --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/ --output-dill /tmp/flutter_tools.QYBCDE/flutter_tool.OVHZMB/app.dill
--packages /home/inits/Desktop/flutter-project/echo4-dashboard/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.QYBCDE/flutter_tools.RDLODI --filesystem-scheme org-dartlang-app --initialize-from-dill build/062e00833251f4c34e967a1a95ff7bd3.cache.dill.track.dill
--platform file:///home/inits/works/dataker/data/flutter/bin/cache/flutter_web_sdk/kernel/ddc_outline_sound.dill --verbosity=error --sound-null-safety
[  +37 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+8587 ms] ../../../.pub-cache/hosted/pub.dev/media_kit_video-1.1.3/lib/src/video/video_texture.dart:118:46: Error: A value of type 'Widget Function(VideoState/*1*/)' can't be assigned
to a
                    variable of type 'Widget Function(VideoState/*2*/)?'.
[   +2 ms]  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../../works/dataker/data/flutter/packages/flutter/lib/src/widgets/framework.dart').
[        ]  - 'VideoState/*1*/' is from 'package:media_kit_video/src/video/video_web.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-1.1.3/lib/src/video/video_web.dart').
[        ]  - 'VideoState/*2*/' is from 'package:media_kit_video/src/video/video_texture.dart'
('../../../.pub-cache/hosted/pub.dev/media_kit_video-1.1.3/lib/src/video/video_texture.dart').
[        ]     this.controls = media_kit_video_controls.AdaptiveVideoControls,
[        ]                                              ^
[+51670 ms] Waiting for connection from debug service on Chrome... (completed in 61.1s)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[   +4 ms] "flutter run" took 63,639ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +226 ms] ensureAnalyticsSent: 222ms
[        ] Running 1 shutdown hook
[  +47 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by alexmercerind** [comment]
You likely imported some implementation files. Please only import the root package in your project.

Our CI succeeds, there's no bug. It's your end.
