### ISSUE TITLE
[Bug Report] Failed assertion while playing seamless example

### ISSUE THREAD

**Issue by canewsin** [media-kit/media-kit#434]
```rust
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Assertion failed: "[Player] has been disposed"
#0      NativePlayer.seek.function
real.dart:727
#1      BasicLock.synchronized 										basic_lock.dart:31 
#2      _SeamlessState.build.										 09.seamless.dart:91 
#3      Future.wait.<anonymous closure> 					(dart:async/future.dart:525:21)
```

**Comment by alexmercerind** [comment]
This was resolved in `main`.
