### ISSUE TITLE
[Android] Exception when taking screenshot

### ISSUE THREAD

**Issue by deckerst** [media-kit/media-kit#569]
A user of Aves reported an issue when trying to capture a screenshot:
- https://github.com/deckerst/aves/issues/799

In the logs, I see various exceptions:
```
10-25 11:25:44.320 11549 11594 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Valid value range is empty: 0
10-25 11:25:44.320 11549 11594 E flutter : #0      List.forEach (dart:core-patch/growable_array.dart)
10-25 11:25:44.320 11549 11594 E flutter : #1      _screenshot (package:media_kit/src/player/native/player/real.dart:2751)
10-25 11:25:44.320 11549 11594 E flutter : #2      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:media_kit/src/player/native/utils/isolates.dart:131)
10-25 11:25:44.320 11549 11594 E flutter : #3      Timeline.timeSync (dart:developer/timeline.dart:171)
10-25 11:25:44.320 11549 11594 E flutter : #4      _IsolateConfiguration.applyAndTime (package:media_kit/src/player/native/utils/isolates.dart:129)
10-25 11:25:44.320 11549 11594 E flutter : #5      _spawn (package:media_kit/src/player/native/utils/isolates.dart:151)
10-25 11:25:44.320 11549 11594 E flutter : #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
10-25 11:25:44.320 11549 11594 E flutter : #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```
```
10-25 11:25:47.920 11549 11594 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Not in inclusive range 0..4: 5
10-25 11:25:47.920 11549 11594 E flutter : #0      List.forEach (dart:core-patch/growable_array.dart)
10-25 11:25:47.920 11549 11594 E flutter : #1      _screenshot (package:media_kit/src/player/native/player/real.dart:2751)
10-25 11:25:47.920 11549 11594 E flutter : #2      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:media_kit/src/player/native/utils/isolates.dart:131)
10-25 11:25:47.920 11549 11594 E flutter : #3      Timeline.timeSync (dart:developer/timeline.dart:171)
10-25 11:25:47.920 11549 11594 E flutter : #4      _IsolateConfiguration.applyAndTime (package:media_kit/src/player/native/utils/isolates.dart:129)
10-25 11:25:47.920 11549 11594 E flutter : #5      _spawn (package:media_kit/src/player/native/utils/isolates.dart:151)
10-25 11:25:47.920 11549 11594 E flutter : #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
10-25 11:25:47.920 11549 11594 E flutter : #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```
```
10-25 11:25:52.177 11549 11594 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): length must be in the range [0, 1073741823].
10-25 11:25:52.177 11549 11594 E flutter : #0      _checkExternalTypedDataLength (dart:ffi-patch/ffi_patch.dart:62)
10-25 11:25:52.177 11549 11594 E flutter : #1      Uint8Pointer.asTypedList (dart:ffi-patch/ffi_patch.dart:611)
10-25 11:25:52.177 11549 11594 E flutter : #2      _screenshot (package:media_kit/src/player/native/player/real.dart:2695)
10-25 11:25:52.177 11549 11594 E flutter : #3      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:media_kit/src/player/native/utils/isolates.dart:131)
10-25 11:25:52.177 11549 11594 E flutter : #4      Timeline.timeSync (dart:developer/timeline.dart:171)
10-25 11:25:52.177 11549 11594 E flutter : #5      _IsolateConfiguration.applyAndTime (package:media_kit/src/player/native/utils/isolates.dart:129)
10-25 11:25:52.177 11549 11594 E flutter : #6      _spawn (package:media_kit/src/player/native/utils/isolates.dart:151)
10-25 11:25:52.177 11549 11594 E flutter : #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
10-25 11:25:52.177 11549 11594 E flutter : #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

I do not experience this myself, so I don't know if the issue is related to specific video formats, or that user environment, or something else entirely.

**Comment by qbing** [comment]
The same issue is found on an old Samsung Galaxy A10. But other android and ios mobile not found this issue.
