### ISSUE TITLE
problem after add media_kit_video package

### ISSUE THREAD

**Issue by TechComet** [media-kit/media-kit#608]
problem on Fedora 39

```
Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db7ef5bf9f (3 days ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2
```

```
[        ] [ +568 ms] release_bundle_linux-x64_assets: Complete
[        ] [  +66 ms] Persisting file store
[        ] [  +11 ms] Done persisting file store
[        ] [  +14 ms] build succeeded.
[        ] [  +13 ms] "flutter assemble" took 33,822ms.
[        ] [ +170 ms] ensureAnalyticsSent: 156ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[   +1 ms] ninja: build stopped: subcommand failed.
[  +29 ms] Building Linux application... (completed in 38.2s)
[   +1 ms] "flutter linux" took 39,472ms.
[   +4 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:186:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:80:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:89:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +197 ms] ensureAnalyticsSent: 183ms
[   +3 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by alexmercerind** [comment]
#595
