### ISSUE TITLE
NPE on subtitleview trim()

### ISSUE THREAD

**Issue by Feichtmeier** [media-kit/media-kit#630]
I have am not using any SubtitleConfiguration so Video should keep its default I think.
Sometimes when I have a fullscreen video I get this exception:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building LayoutBuilder:
flutter: The method 'trim' was called on null.
flutter: Receiver: null
flutter: Tried calling: trim()
flutter: 
flutter: The relevant error-causing widget was:
flutter:   LayoutBuilder
flutter:   LayoutBuilder:file:///C:/Users/wut/AppData/Local/Pub/Cache/hosted/pub.dev/media_kit_video-1.2.4/lib/src/subtitle/subtitle_view.dart:86:12
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
flutter: #1      SubtitleViewState.build.<anonymous closure> (package:media_kit_video/src/subtitle/subtitle_view.dart:106:28)
flutter: #2      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:116:77)
flutter: #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
flutter: #4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:150:12)
flutter: #5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
flutter: #6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
flutter: #7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
flutter: #8      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
flutter: #9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:308:5)
flutter: #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
flutter: #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
flutter: #12     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
flutter: #13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
flutter: #14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
flutter: #15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
flutter: #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
flutter: #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
flutter: #18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
flutter: #19     _invoke (dart:ui/hooks.dart:312:13)
flutter: #20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
flutter: #21     _drawFrame (dart:ui/hooks.dart:283:31)
flutter: 
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

this does not happen on all videos though.

Using

media_kit: ^1.1.10
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4

$ flutter --version
Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db7ef5bf9f (2 weeks ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2

**Comment by pandora-house** [comment]
same problem

**Comment by pandora-house** [comment]
@ Feichtmeier did you try SubtitleViewConfiguration(visible: false)?
