### ISSUE TITLE
Initialization in iOS simulator

### ISSUE THREAD

**Issue by Nei1eveN** [media-kit/media-kit#698]
I'm getting this error when trying to run the package with simulator. Any idea and what needs to be done? Would be really helpful.

```
--------------------------------------------------------------------------------
media_kit: ERROR: MediaKit.ensureInitialized
This indicates that one or more required dependencies could not be located.

Refer to "Installation" section of the README for further details:
GitHub  : https://github.com/media-kit/media-kit#installation
pub.dev : https://pub.dev/packages/media_kit#installation

TIP: Copy-paste required packages from the above link to your pubspec.yaml.

If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find Mpv.framework/Mpv. Please ensure it's presence in the Frameworks folder of the application.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78:9)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47:17)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:34:9)
#3      main (package:wiki_camps/main_development.dart:8:12)
#4      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by Nei1eveN** [comment]
Getting this in Android emulator too

```
I/flutter ( 5128): --------------------------------------------------------------------------------
I/flutter ( 5128): media_kit: ERROR: MediaKit.ensureInitialized
I/flutter ( 5128): This indicates that one or more required dependencies could not be located.
I/flutter ( 5128): 
I/flutter ( 5128): Refer to "Installation" section of the README for further details:
I/flutter ( 5128): GitHub  : https://github.com/media-kit/media-kit#installation
I/flutter ( 5128): pub.dev : https://pub.dev/packages/media_kit#installation
I/flutter ( 5128): 
I/flutter ( 5128): TIP: Copy-paste required packages from the above link to your pubspec.yaml.
I/flutter ( 5128): 
I/flutter ( 5128): If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
I/flutter ( 5128): --------------------------------------------------------------------------------
E/flutter ( 5128): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.
E/flutter ( 5128): #0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78:9)
E/flutter ( 5128): #1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47:17)
E/flutter ( 5128): #2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:36:9)
E/flutter ( 5128): #3      bootstrap.<anonymous closure> (package:wiki_camps/bootstrap.dart:34:14)
E/flutter ( 5128): #4      _rootRun (dart:async/zone.dart:1399:13)
E/flutter ( 5128): #5      _CustomZone.run (dart:async/zone.dart:1301:19)
E/flutter ( 5128): #6      bootstrap (package:wiki_camps/bootstrap.dart:31:29)
E/flutter ( 5128): #7      main (package:wiki_camps/main_development.dart:7:3)
E/flutter ( 5128): #8      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter ( 5128): #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter ( 5128): #10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 5128): 
```

**Comment by Nei1eveN** [comment]
> can you share your pubspec.yaml, most probably you forgot to add the video/audio libs

I doubt. I have them and I followed the installation guide.
![image](https://github.com/media-kit/media-kit/assets/41381713/a07bc0ac-97b2-442d-ab10-903fcc560a33)

**Comment by zezo357** [comment]
```
dependencies:
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.
  ```
  the libs is missing
