### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by mbfakourii** [media-kit/media-kit#999]
Currently, `media-kit` does not support [wasm](https://docs.flutter.dev/platform-integration/web/wasm), I suggest adding this feature.

Logs:
```dart
PS C:\Users\aa\example> flutter run --wasm
Launching lib\main.dart on Chrome in debug mode...
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit_video-1.2.5/lib/src/video_controller/native_video_controller/real.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit_video-1.2.5/lib/src/video_controller/android_video_controller/real.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/allocation.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/utf16.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit_video-1.2.5/lib/src/utils/query_decoders.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/initializer_isolate.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/initializer.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/player/real.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/utils/android_asset_loader.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/utils/android_helper.dart:8:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/initializer_native_event_loop.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/utils/android_content_uri_provider.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/utf8.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/ffi/src/arena.dart:7:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/src/player/native/core/native_library.dart:8:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/media_kit-1.1.11/lib/generated/libmpv/bindings.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi' as ffi;
^
  Command: C:\Users\mbfakourii\Develop\flutter\bin\cache\dart-sdk\bin\dart.exe compile wasm --packages=.dart_tool/package_config.json
  --extra-compiler-option=--platform=C:\Users\mbfakourii\Develop\flutter\bin\cache\flutter_web_sdk\kernel\dart2wasm_platform.dill --extra-compiler-option=--delete-tostring-package-uri=dart:ui
  --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false 
  -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/36335019a8eab588c3c2ea783c618d90505be233/
  --extra-compiler-option=--depfile=C:\Users\aa\example\.dart_tool\flutter_build\db75a67e5b0894465971014c28b1198b\dart2wasm.d -O0 --no-strip-wasm -o
  C:\Users\aa\example\.dart_tool\flutter_build\db75a67e5b0894465971014c28b1198b\main.dart.wasm
  C:\Users\aa\example\.dart_tool\flutter_build\db75a67e5b0894465971014c28b1198b\main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:370:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:334:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:352:11)
<asynchronous suspension>
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                              6.0s
Error: Failed to compile application for the Web.
```

It seems that the `dart:ffi` package is causing problems !

**Comment by alexmercerind** [comment]
Edit the existing PR.
